--- #YAML:1.0
name:                Asterisk-config
version:             0.94
abstract:            The Asterisk config read and write module.
license:             gpl
author:              
    - Sun Bing (hoowa.sun@gmail.com)
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
